apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        image: mcloud-webapp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: "-Xmx128m"