apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  labels:
    app: webapp
spec:
  containers:
  - name: webapp-container
    image: mcloud-webapp:latest
    ports:
    - containerPort: 8080
    env:
      - name: JAVA_OPTS
        value: "-Xmx128m"