apiVersion: v1
kind: Service
metadata:
  name: postgres-mc13-ser
  namespace: mc-13-calculator
spec:
  selector:
    app: postgres-mc13
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: NodePort