apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-mc13-dep
  namespace: mc-13-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-mc13
  template:
    metadata:
      labels:
        app: postgres-mc13
    spec:
      containers:
        - name: postgres-mc13
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "calculator_db"
            - name: POSTGRES_USER
              value: "calculator_user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: calculator-secrets
                  key: db-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}