apiVersion: v1
kind: Secret
metadata:
  name: calculator-secrets
  namespace: mc-13-calculator
type: Opaque
data:
  # Значения должны быть в base64
  db-password: bXlTZWNyZXRQYXNzd29yZDEyMw==  # echo -n 'your-password' | base64
  database-user: Y2FsY3VsYXRvcl91c2Vy
  api-key: c2stMTIzNDU2Nzg5MGFiY2RlZg==
  jwt-secret: bXlTdXBlclNlY3JldEpXVEtleTIwMjQ=