apiVersion: v1
kind: Service
metadata:
  name: calculator-service
  namespace: mcloud-12-calculator
spec:
  selector:
    app: calculator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort