apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-v2-dep
  namespace: mcloud-12-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
      version: v2.0
  template:
    metadata:
      labels:
        app: calculator
        version: v2.0
    spec:
      containers:
        - name: calculator
          image: ghcr.io/pavelkomiss121/mcloud-core:calculator-v2
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-XX:MaxRAMPercentage=75.0"