apiVersion: v1
kind: Service
metadata:
  name: web_server_service
  namespace: staging
spec:
  selector:
    app: web-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort