name: Docker Deploy to GHCR

on:
  push:
    branches: [ master, main, feature/newDocker ]
    paths:
      - 'src/**'
      - 'deploy/**'
      - '.github/workflows/docker-deploy.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pavelkomiss121/mcloud-core

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push WebApp image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile.webapp
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:webapp
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:webapp-${{ github.sha }}

      - name: Build and push TodoApp image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deploy/Dockerfile.todoapp
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:todoapp
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:todoapp-${{ github.sha }}